### ISSUE TITLE
Lookups fail

### ISSUE THREAD

**Issue by ccario83** [p7k/docker-mutalyzer#2]
Great software, and I really appreciate that its dockerized!

I'm having a small issue, however. After starting the container and running the suggested commands, mutation lookups fail. The website functions and looks fine otherwise. 

**Process leading to the error:**
Landing page => Name Checker => First example (AB026906.1:c.274G>T) => Check variant description

**Here's the traceback:**
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/mutalyzer/website/views.py", line 247, in name_checker
    variantchecker.check_variant(description, output)
  File "/usr/local/lib/python2.7/site-packages/mutalyzer/variantchecker.py", line 1743, in check_variant
    retrieved_record = retriever.loadrecord(record_id)
  File "/usr/local/lib/python2.7/site-packages/mutalyzer/Retriever.py", line 771, in loadrecord
    filename = self.fetch(identifier)
  File "/usr/local/lib/python2.7/site-packages/mutalyzer/Retriever.py", line 406, in fetch
    result = self.write(raw_data, name, 1)
  File "/usr/local/lib/python2.7/site-packages/mutalyzer/Retriever.py", line 316, in write
    gi = unicode(record.annotations['gi'])
KeyError: u'gi'
```

**Comment by jfjlaros** [comment]
Judging from the error message, my guess is that this container was made before the NCBI dropped support for GI identifiers in GenBank files. If this is the case, then effectively the Name Checker in this container is no longer usable.

Perhaps @p7k would be willing to create a new container for the latest release of Mutalyzer?

**Comment by p7k** [comment]
Sure thing, @jfjlaros, I could take a crack at it. It's been a while, though...

**Comment by jfjlaros** [comment]
Thanks, that would be great.
